adding two more plays to udracor
dracor-org/udracor pull request #14
Opened 2022-12-05 12:39 UTC by JuliaDudar

2022-12-05 12:45 UTC, JuliaDudar commented
added two plays:
kvitka-osnovianenko-hryhoriy-fedorovych-shelmenko;
kropyvnytskyy-marko-lukych-hlytay-abo-zh-pavuk

2022-12-07 02:01 UTC, cmil requested changes
Hi Julia, welcome to UDraCor. It's great to see a new contributor. Thank you for your pull request! The two new document look very good already. There are a few minor validation and DraCor specific issues. See the respective comments. Maybe we can iron those out before merging. Let me know if you need further support. Also @DanilSko would probably be able to help.

2022-12-12 18:07 UTC, JuliaDudar commented
Hi Carsten, thank you for welcome words and your revision, sorry for the late answer. There are some quetions that I first want to discuss with  @DanilSko before finishing the files.

2022-12-12 18:30 UTC, JuliaDudar commented on tei/kropyvnytskyy-marko-lukych-hlytay-abo-zh-pavuk.xml
> +      <revisionDesc>
done

2022-12-12 18:32 UTC, JuliaDudar commented on tei/kvitka-osnovianenko-hryhoriy-fedorovych-shelmenko-dens.xml
> +    <body>﻿<castList>
done

2022-12-13 08:41 UTC, cmil commented on tei/kropyvnytskyy-marko-lukych-hlytay-abo-zh-pavuk.xml
> +            <surnameКропивницький</surname>
There is a missing `>` for the surname tag.

2022-12-13 09:18 UTC, DanilSko commented on tei/kropyvnytskyy-marko-lukych-hlytay-abo-zh-pavuk.xml
> +            <surnameКропивницький</surname>
Yes, thanks, we noticed that too) I suggested fix for that an a couple of other stuff here yesterday: https://github.com/JuliaDudar/udracor/pull/1

2022-12-13 09:43 UTC, JuliaDudar commented on tei/kropyvnytskyy-marko-lukych-hlytay-abo-zh-pavuk.xml
> +          <person sex="FEMALE" xml:id="1-a_molodytsja">
done

2022-12-13 09:44 UTC, JuliaDudar commented on tei/kropyvnytskyy-marko-lukych-hlytay-abo-zh-pavuk.xml
> +        <author>Марко Кропивницький</author>
done

2022-12-13 09:44 UTC, JuliaDudar commented on tei/kvitka-osnovianenko-hryhoriy-fedorovych-shelmenko-dens.xml
> +        <author>Григорій Квітка-Основ'яненко</author>
done

2022-12-13 13:12 UTC, DanilSko commented
@cmil um, Carsten, is it also possible to have the validation workflow run automatically without manual approval here?

2022-12-20 17:31 UTC, DanilSko commented
Thank you, Carsten! I see that the tests now run for this PR 🙏
(and seem to pass now)

2022-12-23 12:46 UTC, cmil approved these changes

2022-12-23 12:47 UTC, cmil commented
Thanks for making the changes @JuliaDudar and @DanilSko! I will merge now. :)

2022-12-23 12:47 UTC, merged

2022-12-23 13:51 UTC, DanilSko commented
Thank you @cmil! and of course you, @JuliaDudar! Happy holidays!

2022-12-23 14:45 UTC, cmil commented
Happy holidays to you too!

2022-12-23 15:55 UTC, JuliaDudar commented
Thank you guys, wish you happy holidays as well!